#!/bin/bash

# Check if a commit message is provided as an argument
if [ -z "$1" ]; then
  commit_message="Default commit message"
else
  commit_message="$1"
fi

if [ -z "$2" ]; then
  branch="master"
else
  branch="$2"
fi

# Run the Git commands
git add .
git commit -m "$commit_message"
git push -u origin $branch

